<?php

namespace App\AdminBundle\Repository;

/**
 * BannerPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerPlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
