<?php

namespace App\AdminBundle\Repository;

use App\AdminBundle\Entity\Block;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\DependencyInjection\Container;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @var Container
     */
    private $container;

    /**
     * @var Request
     */
    private $request;

    /**
     * @param Container $container
     */
    public function setContainer(Container $container)
    {
        $this->container = $container;
        $this->request = $container->get('request_stack')->getCurrentRequest();
    }

    /**
     * @param Request $request
     */
    public function getPaginationQueryBuilder(Request $request)
    {
        $qb = $this->createQueryBuilder('b');
        $qb
            ->leftJoin('b.translations', 't')
            ->where($qb->expr()->eq('t.locale', $qb->expr()->literal($request->getLocale())));

        if($request->get('query')) {
            $searchArr = explode(' ', trim($request->get('query')));
            $conditions = [];

            foreach ($searchArr as $search) {
                if(strlen($search) >= 3) {
                    $conditions[] = $qb->expr()->like('t.name', $qb->expr()->literal('%' . $search . '%'));
                    $conditions[] = $qb->expr()->like('t.description', $qb->expr()->literal('%' . $search . '%'));
                }
            }

            if(!empty($conditions)) {
                $qb->andWhere(implode(' OR ', $conditions));
            }
        }

        if($request->get('from')) {
            $date = \DateTime::createFromFormat('Y-m-d H:i', $request->get('from'));
            if($date) {
                $qb->andWhere($qb->expr()->gte('b.createdAt', $qb->expr()->literal($date->format('Y-m-d H:i'))));
            }
        }

        if($request->get('to')) {
            $date = \DateTime::createFromFormat('Y-m-d H:i', $request->get('to'));
            if($date) {
                $qb->andWhere($qb->expr()->lte('b.createdAt', $qb->expr()->literal($date->format('Y-m-d H:i'))));
            }
        }

        if($request->get('active')) {
            $qb->andWhere($qb->expr()->eq('b.active', 1));
        }

        return $qb;
    }

    /**
     * Get content by type
     *
     * @param string $type
     */
    public function getContentByType($type)
    {
        $block = $this->findOneByType($type);
        if ($block) {

            return $block->translate()->getDescription();
        }

        return null;
    }
}
