<?php

namespace App\AdminBundle\Repository;

/**
 * BlockTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
