<?php

namespace App\AdminBundle\Repository;

use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\HttpFoundation\Request;

/**
 * CarAccidentHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarAccidentHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @var Container
     */
    private $container;

    /**
     * @var Request
     */
    private $request;

    /**
     * @param Container $container
     */
    public function setContainer(Container $container)
    {
        $this->container = $container;
        $this->request = $container->get('request_stack')->getCurrentRequest();
    }

    /**
     * @param Request $request
     */
    public function getPaginationQueryBuilder(Request $request)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->leftJoin('a.car', 'c');

        if ($this->request->attributes->has('carId')) {
            $qb->where($qb->expr()->eq('c.id', $this->request->attributes->get('carId')));
        }

        if (!$request->get('sort')) {
            $qb->orderBy('c.createdAt', 'DESC');
        }


        return $qb;
    }
}
