<?php

namespace App\AdminBundle\Repository;

/**
 * CarMileageHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarMileageHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
