<?php

namespace App\AdminBundle\Repository;

/**
 * ContentTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentTranslationRepository extends \Doctrine\ORM\EntityRepository
{

}


