<?php

namespace App\AdminBundle\Repository;

/**
 * SettingTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
